config/routes.rb
AdvancedStudyRoom::Application.routes.draw do

  #
  # Devise
  #

  # TODO: Remove dups and generate more readable routes for devise.
  # Look at the devise routes from the 'rake routes' list.
  devise_for :users, controllers: {registrations: :signup} do
    get  'login',     to: 'devise/sessions#new',        as: 'login'
    post 'login',     to: 'devise/sessions#create'
    get  'logout',    to: 'devise/sessions#destroy',    as: 'logout'
    get  'signup',    to: 'signup#new',                 as: 'signup'
    post 'signup',    to: 'signup#create'
  end

  #
  # Users
  #

  get 'profile',                   to: 'users#show'
  get 'users/:id/accounts/new',    to: 'user_accounts#new',        as: 'new_user_account'
  post 'users/:id/accounts/new',   to: 'user_accounts#create'

  #
  # Results
  #

  get 'results',            to: 'results#main_event'
  get 'no_events',          to: 'results#no_events'
  get 'events/:id/results', to: 'results#show', as: 'event_results'

  #
  # Events
  #

  get  'leagues', to: 'events#leagues'
  resources :events, only: [:index, :show] do
    get     :results, to: 'results#index'
    post    :join, on: :member
    delete  :quit, on: :member
  end

  #
  # Admin
  #

  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update] do
      resources :tags, controller: 'event_tags', only: [:new, :create]

      resources :matches, controller: 'event_matches', only: [:index, :new, :create, :destroy]
      # Note the singular on 'resource', this generates routes a different
      # set of routes, use rake routes for more info.
      resource :ruleset, controller: 'event_rulesets', only: [:edit, :update]
      resource :point_ruleset, controller: 'point_rulesets', only: [:edit, :update]
      # Shallow gives us a convenience path to create new tiers for an event
      # and list the tiers of an event, but short paths to edit, update and delete them
      resources :tiers, shallow: true, controller: 'event_tiers', only: [:show, :edit, :update] do
        resource :ruleset, controller: 'tier_rulesets', only: [:edit, :update]
        # Commented, until creation of division is implemented
        # resource :division, controller: 'event_divisions', only: [:new, :create]
      end
      resources :registrations, shallow: true, controller: 'event_registrations', only: [:index] do
        put :assign,  on: :collection
        put :deactivate, on: :member
      end
    end

    resources :matches, controller: 'event_matches', only: [:show, :edit, :update, :destroy] do
      post :validate_and_tag, on: :member
      post :auto_tag, on: :member
      resources :tags, controller: 'match_tags', only: [:new, :create]
    end

    resources :event_tags, only: [:edit, :update, :destroy]
    resources :match_tags, only: [:edit, :update, :destroy]

    # With this route and the one nested under tiers, we make a custom shallow resource
    resources :divisions, controller: 'event_divisions', only: [:edit, :update] do
      resource :ruleset, controller: 'division_rulesets', only: [:edit, :update]
    end

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resources :accounts, shallow: true, controller: 'user_accounts', except: [:index]
    end
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"
  resources :pages
  resources :posts
  get '/',          to: 'results#main_event'
  get ':permalink', to: 'pages#show'
  root to: "results#main_event"

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  event_type         :string(255)
#  server_id          :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  description        :text
#  prizes_description :text
#  starts_at          :datetime
#  ends_at            :datetime
#  opens_at           :datetime
#  closes_at          :datetime
#


class Event < ActiveRecord::Base

  belongs_to :server

  has_one :ruleset, as: :rulesetable, dependent: :destroy
  has_one :point_ruleset, as: :pointable, dependent: :destroy

  has_many :accounts, through: :registrations
  has_many :divisions, through: :tiers, order: '"tiers"."index" ASC, "divisions"."index" ASC'
  has_many :points, dependent: :destroy
  has_many :registrations, include: :account, dependent: :destroy, order: 'LOWER("accounts"."handle") ASC'
  has_many :matches, through: :divisions
  has_many :tags, class_name: 'EventTag', dependent: :destroy, order: 'phrase ASC'
  has_many :tiers, dependent: :destroy, order: '"tiers"."index" ASC'

  scope :live, where('starts_at IS NOT NULL AND DATE(starts_at) <= CURRENT_DATE AND
                      ends_at IS NOT NULL AND CURRENT_DATE <= DATE(ends_at)').
               order('ends_at DESC')

  scope :after, ->(time) { where("starts_at > ?", time) }
  
  attr_accessible :ruleset_id,
                  :name,
                  :start_time
                  :end_time
                  :event_type
                  :server
                  :locked
                  :ruleset_attributes

  accepts_nested_attributes_for :tiers, allow_destroy: true
  accepts_nested_attributes_for :ruleset, allow_destroy: true
  accepts_nested_attributes_for :registrations, allow_destroy: true
  accepts_nested_attributes_for :tags

  def open?
    return true if opens_at.nil? || closes_at.nil?
    opens_at.to_date <= Time.zone.today && Time.zone.today <= closes_at.to_date
  end

  def live?
    return true if starts_at.nil? || ends_at.nil?
    starts_at.to_date <= Time.zone.today && Time.zone.today <= ends_at.to_date
  end

  def ruleset_id=(id)
    self.ruleset = Ruleset.find(id)
  end

  def ruleset_id
    self.ruleset.try :id
  end

  def ruleset?
    ruleset.present?
  end

  def player_count
    registrations.active.count
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  authorize_resource :event
  before_filter :add_breadcrumbs

  def index
    @events = Event.order('starts_at DESC')
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event], without_protection: true)
      redirect_to admin_event_path(@event), flash: {success: 'Event updated' }
    else
      render :edit
    end
  end

  def download_matches
    return unless Rails.env.development?
    event = Event.find(params[:id], include: [:registrations])
    sgf_importer = ASR::SGFImporter.new(server: event.server, ignore_case: true)
    event.registrations.each do |reg|
      matches = sgf_importer.import_matches(handle: reg.handle)
      matches.each(&:save)
    end
    redirect_to matches_event_path(event), flash: {success: 'Event matches were downloaded'}
  end

  private

    def add_breadcrumbs
      @show_breadcrumbs = true
      add_breadcrumb 'Events', admin_events_path
      add_breadcrumb @event.name, admin_event_path(@event) if @event
      add_breadcrumb 'Add', :add if %W(new create).include? params[:action]
      add_breadcrumb 'Edit', :edit if %W(edit update).include? params[:action]
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  load_and_authorize_resource
  before_filter :authorize, except: [:leagues, :show]

  def show
    @event = Event.find(
      params[:id],
      include: [:tags, {tiers: [:registrations, :divisions]}])
    @ruleset = @event.ruleset
  end

  def leagues
    @leagues = Event.order('ends_at DESC').all
  end

  def join
    @event = Event.find(params[:id])
    account = current_user.accounts.where(server_id: @event.server_id).first
    if account
      registration = account.registrations.find_or_create_by_event_id(@event.id)
      registration.update_attributes({active: true, division_id: nil}, without_protection: true)
      redirect_to profile_path,
        flash: {success: "You have joined #{@event.name}, you will be assigned to a division soon"}
    else
      redirect_to new_user_account_path(current_user),
        flash: {error: "Please create an account on the #{@event.server.name} server first"}
    end
  end

  def quit
    reg = current_user.registrations.where(event_id: params[:id]).first
    if reg && !reg.update_attributes({ active: false }, without_protection: true)
      flash[:error] = 'There was an error while deleting your registration'
    end

    redirect_to profile_path, flash: {success: "You have been removed from the event."}
  end

end

app/helpers/events_helper.rb
module EventsHelper

  def sort_column
    if params[:sort] == "handle"
      "LOWER(accounts.handle)"
    elsif Registration.column_names.include?(params[:sort])
       params[:sort]
    else
      "active DESC, points_this_month"
    end
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/views/admin/events/_division_row.html.haml
- if div.blank?
  %td{colspan: 3}
    %p.text-warning
      This tier has no divisions. Please create one.
- else
  %td= div.display_name
  %td= div.registrations.count
  %td
    %ul.inline
      %li= link_to 'Edit', edit_admin_division_path(div)
      %li= link_to 'Edit Ruleset', edit_admin_division_ruleset_path(div)
      / %li= link_to 'Delete', admin_division_path(div),
      /       method: :delete, confirm: 'Are you sure you want to delete this division?'

app/views/admin/events/edit.html.haml
- @title << 'Edit Event'

= simple_form_for @event, url: admin_event_path(@event), html: {class: 'form-horizontal'} do |f|

  = f.input :name
  = f.input :event_type, collection: ['League', 'Tournament'], default: 1, label: 'Event Type'
  = f.input :server_id, collection: Server.all, include_blank: false
  = f.input :opens_at, as: :date
  = f.input :closes_at, as: :date
  = f.input :starts_at, as: :date
  = f.input :ends_at, as: :date
  = f.input :description, input_html: { class: 'markItUp' }
  = f.input :prizes_description, input_html: { class: 'markItUp' }

  .form-actions
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', :back, class: 'btn'

app/views/admin/events/index.html.haml
- @title << 'Events'
%table.table.table-condensed.table-bordered.table-hover
  %thead
    %tr
      %th Name
      %th Players
      %th Type
      %th Server
      %th Actions

  %tbody
    - if @events.empty?
      %tr
        %td{colspan: 5}
          %p.text-warning
            There are no events yet.
            = link_to 'Please create one', new_event_path

    - @events.each do |event|
      %tr
        %td= link_to event.name, event_path(event)
        %td= event.player_count
        %td= event.event_type
        %td= event.server.name
        %td
          %ul.inline
            %li= link_to 'Manage', admin_event_path(event)
            %li= link_to 'Matches', admin_event_matches_path(event)
            %li= link_to 'Edit Details', edit_admin_event_path(event)
            %li= link_to 'Edit Ruleset', edit_admin_event_ruleset_path(event)
            %li= link_to 'Edit Point Rules', edit_admin_event_point_ruleset_path(event)
            %li= link_to 'Assign Players', admin_event_registrations_path(event)
            %li= link_to 'Results', event_results_path(event)
            / %li.pull-right
            /   = link_to "Delete", event_path(event), method: :delete, remote: true,
            /         confirm: 'Are you sure? This action cannot be undone!'

app/views/admin/events/show.html.haml
- @title << @event.name

.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a{href: '#details_tab', data: {toggle: 'tab'}} Details
    %li
      %a{href: '#matches_tab', data: {toggle: 'tab'}} Matches
    %li
      %a{href: '#tags_tab', data: {toggle: 'tab'}} Tags
    %li
      %a{href: '#ruleset_tab', data: {toggle: 'tab'}} Ruleset
    %li
      %a{href: '#point_ruleset_tab', data: {toggle: 'tab'}} Point Ruleset
    %li
      %a{href: '#tiers_tab', data: {toggle: 'tab'}} Tiers


  .tab-content
    #details_tab.tab-pane.active
      = link_to 'Edit Details', edit_admin_event_path(@event), class: 'btn pull-right'
      %table.table.table-condensed.table-bordered.table-hover
        %tbody
          %tr
            %th Event Type
            %td= @event.event_type.to_s.titleize
          %tr
            %th Server
            %td= @event.server.try(:name)
          %tr
            %th Date Range
            %td

              = @event.starts_at.try(:strftime, '%d %m %Y')
              \-
              = @event.ends_at.try(:strftime, '%d %m %Y')
          %tr
            %th Description
            %td= truncate(@event.description, length: 800)
          %tr
            %th Prizes Description
            %td= truncate(@event.prizes_description, length: 800)

    #matches_tab.tab-pane
      = link_to 'Manage Matches', admin_event_matches_path(@event), class: 'btn pull-right'
      %h3 Last 10 Matches
      = render 'admin/event_matches/table', matches: @event.matches.order('completed_at desc').take(10)
      %p.text-success
        %strong Total:
        #{@event.matches.count} matches

    #tags_tab.tab-pane
      .clearfix.pull-right
        = link_to 'Add Tag', new_admin_event_tag_path(@event), class: 'btn'
      = render 'admin/event_tags/table', event: @event

    #ruleset_tab.tab-pane
      .clearfix.pull-right
        = link_to 'Edit Ruleset', edit_admin_event_ruleset_path(@event), class: 'btn'
      = render 'admin/rulesets/table', ruleset: @event.ruleset

    #point_ruleset_tab.tab-pane
      .clearfix.pull-right
        = link_to 'Edit Point Ruleset', edit_admin_event_point_ruleset_path(@event), class: 'btn'
      = render 'admin/rulesets/table', ruleset: @event.point_ruleset

    #tiers_tab.tab-pane
      .clearfix.pull-right
        = link_to 'Assign Players', admin_event_registrations_path(@event), class: 'btn'
      - if @event.tiers.empty?
        = alert(:error) { 'This event has no tiers. Please create one.' }

      %table.table.table-condensed.table-bordered.table-hover
        %thead
          %tr
            %th Position
            %th Tier
            %th Actions
            %th Division
            %th Players
            %th Actions
        %tbody
          - @event.tiers.each do |tier|
            %tr
              %td.middle{rowspan: tier.divisions.count}
                = tier.index
              %td.middle{rowspan: tier.divisions.count}
                = tier.display_name
              %td.middle{rowspan: tier.divisions.count}
                %ul.inline
                  %li= link_to 'Edit', edit_admin_tier_path(tier)
                  %li= link_to 'Edit Ruleset', edit_admin_tier_ruleset_path(tier.ruleset)
                  / %li= link_to 'Delete', admin_tier_path(tier),
                  /       method: :delete, confirm: 'Are you sure you want to delete this tier?'
              = render 'division_row', div: tier.divisions.first
            - tier.divisions[1, tier.divisions.size].each do |div|
              %tr
                = render 'division_row', div: div