config/routes.rb
AdvancedStudyRoom::Application.routes.draw do

  #
  # Devise
  #

  # TODO: Remove dups and generate more readable routes for devise.
  # Look at the devise routes from the 'rake routes' list.
  devise_for :users, controllers: {registrations: :signup} do
    get  'login',     to: 'devise/sessions#new',        as: 'login'
    post 'login',     to: 'devise/sessions#create'
    get  'logout',    to: 'devise/sessions#destroy',    as: 'logout'
    get  'signup',    to: 'signup#new',                 as: 'signup'
    post 'signup',    to: 'signup#create'
  end

  #
  # Users
  #

  get 'profile',                   to: 'users#show'
  get 'users/:id/accounts/new',    to: 'user_accounts#new',        as: 'new_user_account'
  post 'users/:id/accounts/new',   to: 'user_accounts#create'

  #
  # Results
  #

  get 'results',            to: 'results#main_event'
  get 'no_events',          to: 'results#no_events'
  get 'events/:id/results', to: 'results#show', as: 'event_results'

  #
  # Events
  #

  get  'leagues', to: 'events#leagues'
  resources :events, only: [:index, :show] do
    get     :results, to: 'results#index'
    post    :join, on: :member
    delete  :quit, on: :member
  end

  #
  # Admin
  #

  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update] do
      resources :tags, controller: 'event_tags', only: [:new, :create]

      resources :matches, controller: 'event_matches', only: [:index, :new, :create, :destroy]
      # Note the singular on 'resource', this generates routes a different
      # set of routes, use rake routes for more info.
      resource :ruleset, controller: 'event_rulesets', only: [:edit, :update]
      resource :point_ruleset, controller: 'point_rulesets', only: [:edit, :update]
      # Shallow gives us a convenience path to create new tiers for an event
      # and list the tiers of an event, but short paths to edit, update and delete them
      resources :tiers, shallow: true, controller: 'event_tiers', only: [:show, :edit, :update] do
        resource :ruleset, controller: 'tier_rulesets', only: [:edit, :update]
        # Commented, until creation of division is implemented
        # resource :division, controller: 'event_divisions', only: [:new, :create]
      end
      resources :registrations, shallow: true, controller: 'event_registrations', only: [:index] do
        put :assign,  on: :collection
        put :deactivate, on: :member
      end
    end

    resources :matches, controller: 'event_matches', only: [:show, :edit, :update, :destroy] do
      post :validate_and_tag, on: :member
      post :auto_tag, on: :member
      resources :tags, controller: 'match_tags', only: [:new, :create]
    end

    resources :event_tags, only: [:edit, :update, :destroy]
    resources :match_tags, only: [:edit, :update, :destroy]

    # With this route and the one nested under tiers, we make a custom shallow resource
    resources :divisions, controller: 'event_divisions', only: [:edit, :update] do
      resource :ruleset, controller: 'division_rulesets', only: [:edit, :update]
    end

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resources :accounts, shallow: true, controller: 'user_accounts', except: [:index]
    end
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"
  resources :pages
  resources :posts
  get '/',          to: 'results#main_event'
  get ':permalink', to: 'pages#show'
  root to: "results#main_event"

end

app/views/shared/_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= ENV['ASR_ANALYTICS'] %>']);
  _gaq.push(['_trackPageview']);

  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_donate_button.html.haml
%form{action: "https://www.paypal.com/cgi-bin/webscr", method: "post", target: "_top"}
  %input{type: "hidden", name: "cmd", value: "_s-xclick"}
  %input{type: "hidden", name: "hosted_button_id", value: "XFSJ9ZLDRT5WN"}
  %input{type: 'hidden', name: 'submit'}
  %button{type: 'submit', class: 'btn btn-warning btn-large'}
    Donate&nbsp;
    %i.icon-heart
    +
    %i.icon-sitemap
  %img{alt: "", border: "0", src: "https://www.paypalobjects.com/en_US/i/scr/pixel.gif", width: "1", height: "1"}

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  .alert{:class => "#{twitterized_type(type)}"}
    %button{:class => "close", :data => {:dismiss => "alert"}}
      x
    - if type == :error && (flash[:error].kind_of?(ActiveModel::Errors))
      The following errors occurred:
      %br
      - message.messages.each do |key, value|
        = "#{key} #{value}"
        %br
    - else
      = message

app/views/shared/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{:data => {:toggle => "collapse", :target => ".nav-collapse"}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Advanced Study Room", "http://www.advancedstudyroom.com", :class => "brand"

      .nav-collapse
        - if current_user
          .btn-group.pull-right
            %a.btn.dropdown-toggle{:href => "#", :data => {:toggle => "dropdown"}}
              %i.icon-user
              = current_user.email
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "My Profile", profile_path
              %li.divider
              %li
                = link_to "Log Out", logout_path, id: "logout"


        - else
          %ul.nav.pull-right
            %li
              = link_to "Sign Up", signup_path
            %li.divider-vertical
            %li
              = link_to "Log In", login_path

app/views/shared/_navigation_sidebar.haml
.sidebar-nav
  .well{:style => "padding: 8px 0;"}
    %ul.nav.nav-list
      - if current_user
        %li.nav-header
          Your Pages
        %li{class: active_class_for('users#show')}
          = link_to profile_path do
            %i.icon-home
            My Profile

      %li.nav-header
        Main
      %li
        = link_to results_path do
          %i.icon-star
          Current Results

      %li.nav-header
        Leagues
      - Event.order('ends_at DESC').after(Time.zone.now - 6.months).each do |event|
        %li
          = link_to event_path(event) do
            %i.icon-flag
            = event.name
      %li
        = link_to leagues_path do
          %i.icon-archive
          Archives

      - if can? :manage, :all
        %li.nav-header
          Admin
        %li
          = link_to admin_events_path do
            %i.icon-tasks
            Events
        %li
          = link_to admin_users_path do
            %i.icon-user
            Users
        %li
          = link_to posts_path do
            %i.icon-edit
            Posts
        %li
          = link_to pages_path do
            %i.icon-edit
            Pages

app/views/shared/_ruleset_legend.html.haml
%h2 Legend

%dl
  %dt Name
  %dd
    Name of ruleset
  %dt Tag Text
  %dd
    This is the string that will be scanned for to verify that a game played on KGS is a legitimate league game.
  %dt Main Time Min
  %dd
    This is the minimum amount of main game time, in seconds permitted (before byo-yomi). So ten minutes is 60 x 10 = 600.
  %dt Main Time Max
  %dd
    This is the maximum amount of main game time, in seconds.
  %dt Overtime Required
  %dd
    False if absolute time games are permitted, true if they are not.
  %dt J Overtime Allowed
  %dd
    This is a boolean toggle for whether or not games with Japanese overtime settings (byo-yomi periods/stones) will be permitted. If selected, the games will be permitted.
  %dt J OT Min Periods
  %dd
    The minimum number of Japanese overtime periods allowed. For example, 1 period with n number of stones. It does not control the stones per period.
  %dt J OT Max Periods
  %dd
    The maximum number of Japanese overtime periods allowed.
  %dt J OT Min Period Length
  %dd
    This is the Japanese overtime minimum period length, in seconds. In other words, this is the number of seconds a player has to make a move, or lose a period.
  %dt J OT Max Period Length
  %dd
    This is the maximum Japanese overtime period length, in seconds.
  %dt C OT Min Stones
  %dd
    This controls the Canadian overtime minimum number of stones per overtime period. Canadian overtime is seconds/stones: so this controls the number of stones that must be played in n seconds.
  %dt C OT Max Stones
  %dd
    This controls Canadian overtime maximum number of stones that must be played in the overtime period.
  %dt Handicap Default
  %dd
    This sets a default handicap requirement for the league. 0 is recommended.
  %dt Games Per Player
  %dd
    This is the number of games a player must play in order to advance.
  %dt Games Per Opponent
  %dd
    This is the number of games a player is permitted to play per month against a single opponent.