config/routes.rb
AdvancedStudyRoom::Application.routes.draw do

  #
  # Devise
  #

  # TODO: Remove dups and generate more readable routes for devise.
  # Look at the devise routes from the 'rake routes' list.
  devise_for :users, controllers: {registrations: :signup} do
    get  'login',     to: 'devise/sessions#new',        as: 'login'
    post 'login',     to: 'devise/sessions#create'
    get  'logout',    to: 'devise/sessions#destroy',    as: 'logout'
    get  'signup',    to: 'signup#new',                 as: 'signup'
    post 'signup',    to: 'signup#create'
  end

  #
  # Users
  #

  get 'profile',                   to: 'users#show'
  get 'users/:id/accounts/new',    to: 'user_accounts#new',        as: 'new_user_account'
  post 'users/:id/accounts/new',   to: 'user_accounts#create'

  #
  # Results
  #

  get 'results',            to: 'results#main_event'
  get 'no_events',          to: 'results#no_events'
  get 'events/:id/results', to: 'results#show', as: 'event_results'

  #
  # Events
  #

  get  'leagues', to: 'events#leagues'
  resources :events, only: [:index, :show] do
    get     :results, to: 'results#index'
    post    :join, on: :member
    delete  :quit, on: :member
  end

  #
  # Admin
  #

  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update] do
      resources :tags, controller: 'event_tags', only: [:new, :create]

      resources :matches, controller: 'event_matches', only: [:index, :new, :create, :destroy]
      # Note the singular on 'resource', this generates routes a different
      # set of routes, use rake routes for more info.
      resource :ruleset, controller: 'event_rulesets', only: [:edit, :update]
      resource :point_ruleset, controller: 'point_rulesets', only: [:edit, :update]
      # Shallow gives us a convenience path to create new tiers for an event
      # and list the tiers of an event, but short paths to edit, update and delete them
      resources :tiers, shallow: true, controller: 'event_tiers', only: [:show, :edit, :update] do
        resource :ruleset, controller: 'tier_rulesets', only: [:edit, :update]
        # Commented, until creation of division is implemented
        # resource :division, controller: 'event_divisions', only: [:new, :create]
      end
      resources :registrations, shallow: true, controller: 'event_registrations', only: [:index] do
        put :assign,  on: :collection
        put :deactivate, on: :member
      end
    end

    resources :matches, controller: 'event_matches', only: [:show, :edit, :update, :destroy] do
      post :validate_and_tag, on: :member
      post :auto_tag, on: :member
      resources :tags, controller: 'match_tags', only: [:new, :create]
    end

    resources :event_tags, only: [:edit, :update, :destroy]
    resources :match_tags, only: [:edit, :update, :destroy]

    # With this route and the one nested under tiers, we make a custom shallow resource
    resources :divisions, controller: 'event_divisions', only: [:edit, :update] do
      resource :ruleset, controller: 'division_rulesets', only: [:edit, :update]
    end

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resources :accounts, shallow: true, controller: 'user_accounts', except: [:index]
    end
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"
  resources :pages
  resources :posts
  get '/',          to: 'results#main_event'
  get ':permalink', to: 'pages#show'
  root to: "results#main_event"

end

app/models/event_tag.rb
# == Schema Information
#
# Table name: event_tags
#
#  id         :integer          not null, primary key
#  phrase     :string(255)
#  event_id   :integer
#  node_limit :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EventTag < ActiveRecord::Base

  before_validation :format_phrase

  belongs_to :event

  attr_accessible :phrase,
                  :node_limit

  validates :event_id,
    presence: true
  validates :phrase,
    presence: true,
    uniqueness: {scope: :event_id},
    format: {with: /^\s*\#?[^\s]+\s*$/, message: "can't have spaces"}
  validates :node_limit,
    presence: true,
    numericality: {only_integer: true, greater_than_or_equal_to: 0}


  def after_initialize
    self.node_limit ||= 0
  end

  private

    def format_phrase
      tag_phrase = phrase.strip
      self.phrase = '#' + tag_phrase unless tag_phrase =~ /^\#/
    end

end

app/controllers/admin/event_tags_controller.rb
class Admin::EventTagsController < ApplicationController

  load_and_authorize_resource :event, only: [:new, :create]
  load_and_authorize_resource :event_tag, shallow: true, through_association: :tags
  before_filter :add_breadcrumbs

  def new
  end

  def create
    @event_tag = @event.tags.build(params[:event_tag])
    if @event_tag.save
      redirect_to admin_event_path(@event), flash: {success: 'Tag was created'}
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @event_tag.update_attributes(params[:event_tag])
      redirect_to admin_event_path(@event_tag.event), flash: {success: 'Tag was updated'}
    else
      render :edit
    end
  end

  def destroy
    flash[:success] = 'Tag was deleted' if @event_tag.destroy
    redirect_to admin_event_path(@event_tag.event)
  end

  private

    def add_breadcrumbs
      @show_breadcrumbs = true
      event = @event || @event_tag.event
      add_breadcrumb 'Events', admin_events_path
      add_breadcrumb event.name, admin_event_path(event)
      add_breadcrumb 'Add Tag', :new if %W(new create).include? params[:action]
      add_breadcrumb 'Edit Tag', :edit if %W(edit update).include? params[:action]
    end

end

app/views/admin/event_tags/_table.html.haml
%table.table.table-condensed.table-bordered.table-hover
  %thead
    %tr
      %th Phrase
      %th Move Limit
      %th Actions

  %tbody
    - if event.tags.empty?
      %tr
        %td{colspan: 3}
          %p.text-warning
            There are not tags. Please
            = link_to 'add one.', new_admin_event_tag_path(event)

    - event.tags.each do |tag|
      %tr
        %td= tag.phrase
        %td= number_with_delimiter(tag.node_limit)
        %td.actions
          %ul.inline
            %li= link_to 'Edit', edit_admin_event_tag_path(tag)
            %li= link_to 'Delete', admin_event_tag_path(tag),
                  method: :delete, confirm: 'Are you sure you want to delete this tag?'

app/views/admin/event_tags/edit.html.haml
- @title << 'Edit event tag'

= simple_form_for @event_tag, url: admin_event_tag_path(@event_tag), validate: true, html: {class: 'form-horizontal'} do |f|

  = f.input :phrase
  = f.input :node_limit, label: 'Move Limit'

  .form-actions
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Back', :back, class: 'btn'

app/views/admin/event_tags/new.html.haml
- @title << 'Add event tag'

= simple_form_for @event_tag, url: admin_event_tags_path(@event), validate: true, html: {class: 'form-horizontal'} do |f|

  = f.input :phrase, autofocus: true
  = f.input :node_limit, label: 'Move Limit'

  .form-actions
    = f.submit 'Create', class: 'btn btn-primary'
    = link_to 'Back', :back, class: 'btn'