config/routes.rb
AdvancedStudyRoom::Application.routes.draw do

  #
  # Devise
  #

  # TODO: Remove dups and generate more readable routes for devise.
  # Look at the devise routes from the 'rake routes' list.
  devise_for :users, controllers: {registrations: :signup} do
    get  'login',     to: 'devise/sessions#new',        as: 'login'
    post 'login',     to: 'devise/sessions#create'
    get  'logout',    to: 'devise/sessions#destroy',    as: 'logout'
    get  'signup',    to: 'signup#new',                 as: 'signup'
    post 'signup',    to: 'signup#create'
  end

  #
  # Users
  #

  get 'profile',                   to: 'users#show'
  get 'users/:id/accounts/new',    to: 'user_accounts#new',        as: 'new_user_account'
  post 'users/:id/accounts/new',   to: 'user_accounts#create'

  #
  # Results
  #

  get 'results',            to: 'results#main_event'
  get 'no_events',          to: 'results#no_events'
  get 'events/:id/results', to: 'results#show', as: 'event_results'

  #
  # Events
  #

  get  'leagues', to: 'events#leagues'
  resources :events, only: [:index, :show] do
    get     :results, to: 'results#index'
    post    :join, on: :member
    delete  :quit, on: :member
  end

  #
  # Admin
  #

  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update] do
      resources :tags, controller: 'event_tags', only: [:new, :create]

      resources :matches, controller: 'event_matches', only: [:index, :new, :create, :destroy]
      # Note the singular on 'resource', this generates routes a different
      # set of routes, use rake routes for more info.
      resource :ruleset, controller: 'event_rulesets', only: [:edit, :update]
      resource :point_ruleset, controller: 'point_rulesets', only: [:edit, :update]
      # Shallow gives us a convenience path to create new tiers for an event
      # and list the tiers of an event, but short paths to edit, update and delete them
      resources :tiers, shallow: true, controller: 'event_tiers', only: [:show, :edit, :update] do
        resource :ruleset, controller: 'tier_rulesets', only: [:edit, :update]
        # Commented, until creation of division is implemented
        # resource :division, controller: 'event_divisions', only: [:new, :create]
      end
      resources :registrations, shallow: true, controller: 'event_registrations', only: [:index] do
        put :assign,  on: :collection
        put :deactivate, on: :member
      end
    end

    resources :matches, controller: 'event_matches', only: [:show, :edit, :update, :destroy] do
      post :validate_and_tag, on: :member
      post :auto_tag, on: :member
      resources :tags, controller: 'match_tags', only: [:new, :create]
    end

    resources :event_tags, only: [:edit, :update, :destroy]
    resources :match_tags, only: [:edit, :update, :destroy]

    # With this route and the one nested under tiers, we make a custom shallow resource
    resources :divisions, controller: 'event_divisions', only: [:edit, :update] do
      resource :ruleset, controller: 'division_rulesets', only: [:edit, :update]
    end

    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resources :accounts, shallow: true, controller: 'user_accounts', except: [:index]
    end
  end

  mount Markitup::Rails::Engine, at: "markitup", as: "markitup"
  resources :pages
  resources :posts
  get '/',          to: 'results#main_event'
  get ':permalink', to: 'pages#show'
  root to: "results#main_event"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  admin                  :boolean          default(FALSE), not null
#  email                  :string(255)      default(""), not null
#  username               :string(255)
#  first_name             :string(255)
#  last_name              :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer          default(0)
#  unlock_token           :string(255)
#  locked_at              :datetime
#  authentication_token   :string(255)
#

class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :token_authenticatable

  has_many :accounts, validate: true, autosave: true, dependent: :destroy
  has_many :awards
  has_many :events, through: :registrations
  has_many :registrations, through: :accounts
  has_many :servers, through: :accounts

  scope :admins, where(admin: true)
  scope :normal, where(admin: false)

  attr_accessor   :login
  attr_accessible :login,
                  :username,
                  :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :first_name,
                  :last_name,
                  :accounts_attributes

  accepts_nested_attributes_for :accounts, allow_destroy: true

  validates :email,
              presence: true,
              uniqueness: {case_sensitive: false},
              format: { with: /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i,
                        message: 'is an invalid email' }
  validates :username,  presence: true,
                        uniqueness: {case_sensitive: false}
  validates :password, confirmation: true, unless: Proc.new { |u| u.password.blank? }

  before_save :strip_whitespaces

  def strip_whitespaces
    self.username.strip!
    self.email.strip!
  end

  def registered_for_anything?
    if registrations.any?
      registrations.any? { |r| r.active? }
    else
      false
    end

  end

  def joined_event? event_id
    events.exists?(id: event_id)
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).
      where(['lower(username) = :login OR lower(email) = :login', login: login.downcase]).
      first
    else
      email = conditions.delete(:email)
      conditions[:email] = email.to_s.downcase if email
      where(conditions).first
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  authorize_resource :user
  before_filter :load_user, except: [:index]
  before_filter :add_breadcrumbs

  def index
    @users = User.includes(:accounts)
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user], without_protection: true)
      redirect_to admin_user_path(@user), flash: {success: 'User updated' }
    else
      render :edit
    end
  end

  def destroy
    is_oneself = current_user.id == @user.id
    if is_oneself
      flash[:error] = 'You can\' delete yourself'
    elsif !@user.destroy
      flash[:error] = 'Error while deleting user'
    end
    redirect_to admin_users_path
  end

  private

    def add_breadcrumbs
      @show_breadcrumbs = true
      add_breadcrumb 'Users', admin_users_path
      add_breadcrumb @user.username, admin_user_path(@user) if @user
      add_breadcrumb 'Add', :add if %W(new create).include? params[:action]
      add_breadcrumb 'Edit', :edit if %W(edit update).include? params[:action]
    end

    def load_user
      @user = User.find_by_id(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  authorize_resource

  def show
    @user = User.find(current_user.id, include: {accounts: [:server, :registrations]})
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def link_to_results(name, registration)
    results_path = event_results_path(registration.event, division_id: registration.division_id)
    link_to(name, results_path)
  end

  def can_add_account?(user)
    user.accounts.count < Server.count
  end

  def can_join_events?(user)
    user.registrations.active.count < Event.count
  end

end

app/views/admin/users/_account_row.html.haml
- if account.blank?
  %td{colspan: 3}
    %p.text-warning
      This user has no accounts.
- else
  %td= account.handle
  %td
    %ul.inline
      %li= link_to 'Edit', edit_admin_account_path(account)
      %li= link_to 'Delete', admin_account_path(account),
            method: :delete, confirm: 'Are you sure you want to delete this account?'

app/views/admin/users/_table.html.haml
%table.table.table-condensed.table-bordered.table-hover
  %thead
    %tr
      %th Username
      %th Actions

  %tbody
    - if users.empty?
      %tr
        %td{colspan: 3}
          %p.text-warning
            There are no users.

    - users.each do |user|
      %tr
        %td= link_to "#{user.username}", admin_user_path(user)
        %td.actions
          = link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-small'
          = link_to 'Delete', admin_user_path(user), class: 'btn btn-small btn-danger',
              method: :delete,
              confirm: 'Are you sure you want to delete this user?'

app/views/admin/users/edit.html.haml
- @title << 'Edit User'

= simple_form_for @user, url: admin_user_path(@user), html: {class: 'form-horizontal'} do |f|

  = f.input :admin, wrapper: :checkbox
  = f.input :username
  = f.input :email
  = f.input :first_name
  = f.input :last_name

  .form-actions
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', :back, class: 'btn'

app/views/admin/users/index.html.haml
- @title << "Users"

.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a{href: "#tab1", data: {toggle: "tab"}} Admins
    %li
      %a{href: "#tab2", data: {toggle: "tab"}} Users

  .tab-content
    #tab1.tab-pane.active
      = render "admin/users/table", users: @users.admins

    #tab2.tab-pane
      %table.table.table-condensed.table-bordered.table-hover
        %thead
          %tr
            %th Username
            %th Actions
            %th Accounts
            %th Actions

        %tbody
          - if @users.empty?
            %tr
              %td{colspan: 4}
                %p.text-warning
                  There are no users.

          - @users.each do |user|
            %tr
              %td= link_to "#{user.username}", admin_user_path(user)
              %td.actions
                = link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-small'
                = link_to 'Delete', admin_user_path(user), class: 'btn btn-small btn-danger',
                    method: :delete,
                    confirm: 'Are you sure you want to delete this user?'
              - if user.accounts.empty?
                %td{colspan: 2}
                  %p.text-warning
                    This user has no accounts.
              - else
                - user.accounts.each do |account|
                  = render 'account_row', account: account

app/views/admin/users/show.html.haml
- @title << @user.username

%h2
  User Details
  = link_to 'Edit user', edit_admin_user_path(@user), class: 'btn pull-right'

%table.table.table-condensed.table-hover.table-bordered
  %thead
    %tr
      %th Email
      %th Username
      %th Admin?
      %th Sign in count
  %tbody
    %td= @user.email
    %td= @user.username
    %td= yes_no @user.admin?
    %td= @user.sign_in_count

%h2
  Events
  / = link_to 'Add to Event', new_

%table.table.table-condensed.table-hover.table-bordered
  %thead
    %tr
      %th Event
      %th Division
      %th Account Handle
      %th Server
      %th Actions
  %tbody
    - @user.registrations.active.each do |reg|
      %tr
        %td= link_to_results(reg.event.name, reg)
        %td= link_to_results(reg.division.try(:name) || 'Pending...', reg)
        %td= link_to "#{reg.account.handle}", admin_account_path(reg.account)
        %td= reg.account.server.name
        %td= link_to 'Remove', deactivate_admin_registration_path(reg), method: :put, class: 'btn btn-mini btn-danger'

%h2
  Accounts
%table.table.table-condensed.table-hover.table-bordered
  %thead
    %tr
      %th Server
      %th Rank
      %th Handle
      %th Events Joined
      %th Actions
  %tbody
    - @user.accounts.each do |account|
      %tr
        %td= account.server.name
        %td= account.rank ? Utilities.format_rank(account.rank) : "Pending..."
        %td= link_to "#{account.handle}", admin_account_path(account)
        %td= account.registrations.active.count
        %td
          = link_to 'Edit', edit_admin_account_path(account), class: 'btn btn-mini'
          = link_to 'Delete', admin_account_path(account), method: :delete, class: 'btn btn-mini btn-danger',
            confirm: 'Are you sure you want to delete your account? All your matches will be lost.'